### ISSUE TITLE
OnaniCore TODO

### ISSUE THREAD

**Issue by kapsikkum** [Onani-Dev/Onani#8]
- [ ] Finish Database controller (requires way to get, add, remove and change objects)

- [ ] Post, user, tag, collection objects

- [ ] Update valueerrors to custom exceptions

- [ ] add scrapers, and service to automatically check for new posts on sites

- [ ] add easily changeable file controller
